id: I14CBC54B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T14:14:19+00:00'
last_modified: '2022-06-07T18:49:21.775808+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18997
  title: སྤྱོད་འཇུག་རྣམ་བཤད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
  base:
    31D6:
      image_group_id: I8LS18999
      title: ''
      total_pages: 418
      order: 1
      base_file: 31D6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
