id: P003280
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18997
  title: སྤྱོད་འཇུག་རྣམ་བཤད།
  author: ''
  volumes:
    991a726eef5a4935ba829365b05bd3c4:
      image_group_id: I8LS18999
      title: ''
      volume_number: 1
      total_pages: 418
      base_file: v001.txt
