id: P003280
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 10:52:18.443484
source_metadata:
  id: bdr:W8LS18997
  title: སྤྱོད་འཇུག་རྣམ་བཤད།
  author: ''
  volumes:
    991a726eef5a4935ba829365b05bd3c4:
      image_group_id: I8LS18999
      title: ''
      volume_number: 1
      total_pages: 418
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
